# Generated by Django 5.1.5 on 2025-04-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('duration_days', models.PositiveIntegerField()),
                ('activities', models.CharField(choices=[('hiking', 'Hiking'), ('camping', 'Camping'), ('both', 'Both')], max_length=10)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('group_size', models.PositiveIntegerField()),
                ('trip_name', models.CharField(max_length=100)),
            ],
        ),
    ]
