# Generated by Django 5.1.5 on 2025-04-16 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_trippreferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trippreferences',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_number', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('group_size', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=255)),
                ('activity', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField()),
                ('difficulty', models.CharField(max_length=50)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
