# Generated by Django 5.1.5 on 2025-04-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_trippreferences_user_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trippreferences',
            name='itinerary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
