# Generated by Django 5.1.5 on 2025-04-17 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_trippreferences_itinerary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='trip_number',
        ),
        migrations.AddField(
            model_name='trip',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
