# Generated by Django 5.1.5 on 2025-04-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_trip_trip_number_trip_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='itinerary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
