# Generated by Django 5.1.5 on 2025-04-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_trip_itinerary_trip_trip_name_alter_trip_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='visible_in_saved',
            field=models.BooleanField(default=True),
        ),
    ]
