# Generated by Django 5.1.5 on 2025-02-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, default='default-movie.png', null=True, upload_to='movie_images/'),
        ),
    ]
